<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'name' => 'Pengantar Etika Bisnis',
                'merchant_id' => 1,
                'description' => 'Barang bekas ini adalah sebuah buku "Pengantar Etika Bisnis", yang telah digunakan sebelumnya. Meskipun kondisinya bekas dan mungkin memiliki sedikit kerusakan seperti coretan atau lipatan, isi dan pengetahuan yang tersedia di dalamnya tetap berharga. Buku ini tetap menjadi sumber yang berguna untuk memahami prinsip-prinsip etika dalam konteks bisnis.',
                'price' => 50000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0004.jpg',
                'category_id' => 1,
                'condition' => 'Very Good',
                'stock' => 1,
                'discount' => 10,
                'time_usage' => 10,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 2,
                'name' => 'Pendidikan Agama Islam',
                'merchant_id' => 1,
                'description' => 'Barang bekas ini adalah sebuah buku "Pendidikan Agama Islam". Meskipun telah digunakan sebelumnya, buku ini masih menyajikan pengetahuan penting tentang ajaran dan nilai-nilai dalam Islam. Meski mungkin terdapat beberapa tanda penggunaan seperti lipatan atau coretan, isi dan pelajarannya tetap berharga bagi yang ingin memperdalam pemahaman tentang agama Islam.',
                'price' => 80000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0005.jpg',
                'category_id' => 1,
                'condition' => 'Very Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 3,
                'name' => 'Buku Akuntasi',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah buku Akuntansi. Walaupun sudah digunakan sebelumnya, buku ini masih berisi informasi yang penting mengenai konsep-konsep dasar akuntansi dan praktik-praktiknya. Meskipun mungkin terdapat sedikit tanda penggunaan seperti lipatan halaman atau coretan, isi buku ini tetap berharga bagi yang ingin mempelajari atau merujuk materi akuntansi.',
                'price' => 70000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0006.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => false,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 4,
                'name' => 'Skincare',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah produk perawatan kulit (skincare). Meskipun telah digunakan sebelumnya, produk ini masih menyajikan manfaat bagi perawatan kulit. Meskipun kemasannya mungkin sudah agak aus atau terbuka, isinya masih dapat digunakan untuk perawatan kulit Anda.',
                'price' => 60000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0007.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => false,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 5,
                'name' => 'Pakaian Tidur',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah pakaian tidur yang nyaman untuk digunakan saat beristirahat. Meskipun telah digunakan sebelumnya, pakaian tidur ini masih memiliki kenyamanan dan fungsionalitasnya. Meskipun mungkin ada sedikit tanda pemakaian seperti bobotan atau warna yang sedikit pudar, pakaian tidur ini masih cocok digunakan untuk mendapatkan istirahat yang nyenyak.',
                'price' => 60000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0008.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => false,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 6,
                'name' => 'Rok',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah rok, pakaian yang sering dipakai oleh wanita. Walaupun barang ini bekas, rok ini masih memiliki potensi untuk memberikan gaya yang menarik. Meskipun mungkin terdapat beberapa tanda penggunaan seperti bekas lipatan atau sedikit keausan, rok ini masih dapat menjadi pilihan yang baik untuk digunakan dalam berbagai kesempatan.',
                'price' => 50000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0009.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 7,
                'name' => 'Buku Akuntansi',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah buku akuntansi. Meskipun sudah digunakan sebelumnya, buku ini masih berisi informasi penting mengenai konsep-konsep dasar akuntansi serta praktiknya. Walaupun mungkin terdapat beberapa tanda penggunaan seperti lipatan halaman atau coretan, isi buku ini tetap berharga bagi yang ingin mempelajari atau merujuk materi akuntansi.',
                'price' => 20000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0010.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 8,
                'name' => 'Tas',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah tas. Walaupun sudah digunakan sebelumnya, tas ini masih memiliki fungsi yang baik untuk membawa barang-barang Anda sehari-hari. Mungkin terdapat beberapa tanda penggunaan seperti goresan atau sedikit keausan di bagian-bagian tertentu, namun tas ini masih layak digunakan dan cocok untuk berbagai kesempatan.',
                'price' => 60000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0011.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 9,
                'name' => 'Jam Tangan',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah jam tangan. Walaupun sudah digunakan sebelumnya, jam ini masih berfungsi dengan baik untuk menunjukkan waktu. Mungkin terdapat beberapa tanda penggunaan seperti goresan kecil atau keausan pada bagian strap atau casing, namun jam ini masih dapat dipakai dengan nyaman dan dapat diandalkan untuk penggunaan sehari-hari.',
                'price' => 100000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0012.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 10,
                'name' => 'Celana',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah celana. Walaupun sudah digunakan sebelumnya, celana ini masih memiliki potensi untuk memberikan kenyamanan dan gaya yang sesuai. Mungkin terdapat beberapa tanda penggunaan seperti sedikit keausan atau lipatan, namun celana ini masih cocok digunakan dalam berbagai kesempatan, baik untuk santai maupun formal, tergantung pada gaya dan preferensi Anda.',
                'price' => 50000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0013.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],
            [
                'id' => 11,
                'name' => 'Kerudung',
                'merchant_id' => 1,
                'description' => 'Barang ini adalah sebuah kerudung, item yang sering digunakan untuk menutupi kepala dan rambut, terutama dalam konteks busana Muslim. Meskipun barang ini bekas, kerudung ini masih dapat memberikan penampilan yang sopan dan sesuai dengan nilai-nilai keagamaan atau preferensi pribadi Anda. Meskipun mungkin ada sedikit tanda penggunaan seperti lipatan atau perubahan warna yang sedikit, kerudung ini tetap dapat digunakan untuk menambahkan sentuhan yang elegan pada penampilan Anda.',
                'price' => 10000,
                'image' => 'https://arcudskzafkijqukfool.supabase.co/storage/v1/object/public/Goodsvind/IMG-20240424-WA0014.jpg',
                'category_id' => 1,
                'condition' => 'Good',
                'stock' => 1,
                'discount' => 0,
                'time_usage' => 0,
                'is_promotion' => true,
                'status_approved' => 'Accepted',
            ],

        ];


        foreach ($products as $product) {
            \App\Models\Product::create($product);
        }
    }
}
